SELECT_ALL_REMINDERS = "SELECT * from REMINDERS;"
DELETE_FROM_REMINDERS = "DELETE FROM REMINDERS;"
DELETE_SPEC_REMINDER = "DELETE FROM REMINDERS WHERE (TOPIC=?);"
SELECT_TOPIC_FROM_REM_WRT_TIME_DATE = "SELECT TOPIC FROM REMINDERS WHERE TIME=? AND DATE=?;"
